
CREATE DATABASE IF NOT EXISTS dmt_dataloader
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE dmt_dataloader;

DROP TABLE IF EXISTS epicor_vendor_bank;

CREATE TABLE epicor_vendor_bank (
  Company                  VARCHAR(8)    NOT NULL DEFAULT '',
  VendorNum                INT           NOT NULL DEFAULT 0,
  BankID                   VARCHAR(9)    NOT NULL DEFAULT '',
  BankName                 VARCHAR(50)   NOT NULL DEFAULT '',
  Address1                 VARCHAR(50)   NOT NULL DEFAULT '',
  Address2                 VARCHAR(50)   NOT NULL DEFAULT '',
  Address3                 VARCHAR(50)   NOT NULL DEFAULT '',
  City                     VARCHAR(50)   NOT NULL DEFAULT '',
  State                    VARCHAR(50)   NOT NULL DEFAULT '',
  PostalCode               VARCHAR(10)   NOT NULL DEFAULT '',
  CountryNum               INT           NOT NULL DEFAULT 0,
  BankAcctNumber           VARCHAR(34)   NOT NULL DEFAULT '',
  NameOnAccount            VARCHAR(50)   NOT NULL DEFAULT '',
  SwiftNum                 VARCHAR(11)   NOT NULL DEFAULT '',
  PMUID                    INT           NOT NULL DEFAULT 0,
  BankBranchCode           VARCHAR(30)   NOT NULL DEFAULT '',
  IBANCode                 VARCHAR(34)   NOT NULL DEFAULT '',
  SECreditTransNum         VARCHAR(6)    NOT NULL DEFAULT '',
  LegalName                VARCHAR(200)  NOT NULL DEFAULT '',
  CorrespAccount           VARCHAR(34)   NOT NULL DEFAULT '',
  LocalBIC                 VARCHAR(12)   NOT NULL DEFAULT '',
  BankPersonCode           VARCHAR(20)   NOT NULL DEFAULT '',
  VendAccountType          VARCHAR(8)    NOT NULL DEFAULT '',
  CardCode                 VARCHAR(8)    NOT NULL DEFAULT '',
  BankGiroAcctNbr          VARCHAR(34)   NOT NULL DEFAULT '',
  BankRefCode              VARCHAR(4)    NOT NULL DEFAULT '',
  AllowAsAltRemitToBank    TINYINT(1)    NOT NULL DEFAULT 0,
  DFIIdentification        VARCHAR(9)    NOT NULL DEFAULT '',

  SysRevID                 BINARY(8)     NOT NULL DEFAULT (RANDOM_BYTES(8)),
  SysRowID                 BINARY(16)    NOT NULL DEFAULT (UUID_TO_BIN(UUID())),

  CHDTAID                  VARCHAR(6)    NOT NULL DEFAULT '',
  CHISRPartyID             VARCHAR(9)    NOT NULL DEFAULT '',
  FeeOwnership             VARCHAR(3)    NOT NULL DEFAULT '',
  POBankAcctNum            VARCHAR(9)    NOT NULL DEFAULT '',
  BankCustNum              VARCHAR(12)   NOT NULL DEFAULT '',
  BankCustNumberStartPos   INT           NOT NULL DEFAULT 0,
  BankCustNumberLen        INT           NOT NULL DEFAULT 0,
  BAddress1                VARCHAR(50)   NOT NULL DEFAULT '',
  BAddress2                VARCHAR(50)   NOT NULL DEFAULT '',
  BAddress3                VARCHAR(50)   NOT NULL DEFAULT '',
  BankCharges              VARCHAR(8)    NOT NULL DEFAULT '',
  BankCnstSymbol           VARCHAR(8)    NOT NULL DEFAULT '',
  BankSpecSymbol           VARCHAR(32)   NOT NULL DEFAULT '',
  BankType                 VARCHAR(20)   NOT NULL DEFAULT '',
  BCity                    VARCHAR(50)   NOT NULL DEFAULT '',
  BCountryNum              INT           NOT NULL DEFAULT 0,
  BPostalCode              VARCHAR(10)   NOT NULL DEFAULT '',
  BState                   VARCHAR(50)   NOT NULL DEFAULT '',
  NOChequeCode             VARCHAR(1)    NOT NULL DEFAULT '',
  NOFeeCostCode            VARCHAR(1)    NOT NULL DEFAULT '',
  ReceiverName             VARCHAR(30)   NOT NULL DEFAULT '',
  ReceivingBankName        VARCHAR(15)   NOT NULL DEFAULT '',
  ReceivingBankNum         VARCHAR(4)    NOT NULL DEFAULT '',
  ReceivingBranchName      VARCHAR(15)   NOT NULL DEFAULT '',
  ReceivingBranchNum       VARCHAR(3)    NOT NULL DEFAULT '',
  SEBankFeeCostOwner       VARCHAR(1)    NOT NULL DEFAULT '',
  PEDetractionsNBA         TINYINT(1)    NOT NULL DEFAULT 0,
  MXSATCode                VARCHAR(10)   NOT NULL DEFAULT '',
  MXSATNameShort           VARCHAR(50)   NOT NULL DEFAULT '',
  MXSATNameFull            VARCHAR(500)  NOT NULL DEFAULT '',
  DKCreditorNum            VARCHAR(8)    NOT NULL DEFAULT '',
  PayID                    VARCHAR(50)   NOT NULL DEFAULT '',
  ClearSystemIDCode        VARCHAR(5)    NOT NULL DEFAULT '',
  MemberID                 VARCHAR(30)   NOT NULL DEFAULT '',
  DistrictName             VARCHAR(50)   NOT NULL DEFAULT '',
  StreetName               VARCHAR(50)   NOT NULL DEFAULT '',
  BuildingNumber           VARCHAR(50)   NOT NULL DEFAULT '',
  Floor                    VARCHAR(50)   NOT NULL DEFAULT '',
  Room                     VARCHAR(50)   NOT NULL DEFAULT '',
  PostBox                  VARCHAR(50)   NOT NULL DEFAULT '',
  BDistrictName            VARCHAR(50)   NOT NULL DEFAULT '',
  BStreetName              VARCHAR(50)   NOT NULL DEFAULT '',
  BBuildingNumber          VARCHAR(50)   NOT NULL DEFAULT '',
  BFloor                   VARCHAR(50)   NOT NULL DEFAULT '',
  BRoom                    VARCHAR(50)   NOT NULL DEFAULT '',
  BPostBox                 VARCHAR(50)   NOT NULL DEFAULT '',

  PRIMARY KEY (Company, VendorNum, BankID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;
